reenable version number check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20588,9 +20588,11 @@ scipver=`awk '/define SCIP_VERSION/ {print $3}' ${srcdir}/scip/src/scip/def.h`
 scipsubver=`awk '/define SCIP_SUBVERSION/ {print $3}' ${srcdir}/scip/src/scip/def.h`
 echo "$as_me:$LINENO: result: ${scipver}.${scipsubver}" >&5
 echo "${ECHO_T}${scipver}.${scipsubver}" >&6
-#if test $scipver -lt 210 -o $scipver -ge 220 ; then
-#  AC_MSG_ERROR(["Incorrect SCIP version. This build system is made for SCIP 2.1.x"])
-#fi
+if test $scipver -lt 210 -o $scipver -ge 220 ; then
+  { { echo "$as_me:$LINENO: error: \"Incorrect SCIP version. This build system is made for SCIP 2.1.x\"" >&5
+echo "$as_me: error: \"Incorrect SCIP version. This build system is made for SCIP 2.1.x\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 #############################################################################
 #                       Check for external libraries                        #
