put back check for SCIP version number

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21026,6 +21026,22 @@ fi
 }
 
 #############################################################################
+#                         Check SCIP version number                         #
+#############################################################################
+
+echo "$as_me:$LINENO: checking SCIP version" >&5
+echo $ECHO_N "checking SCIP version... $ECHO_C" >&6
+scipver=`awk '/define SCIP_VERSION/ {print $3}' ${srcdir}/scip/src/scip/def.h`
+scipsubver=`awk '/define SCIP_SUBVERSION/ {print $3}' ${srcdir}/scip/src/scip/def.h`
+echo "$as_me:$LINENO: result: ${scipver}.${scipsubver}" >&5
+echo "${ECHO_T}${scipver}.${scipsubver}" >&6
+if test $scipver -lt 200 -o $scipver -ge 210 ; then
+  { { echo "$as_me:$LINENO: error: \"Incorrect SCIP version. This build system is made for SCIP 2.0.x\"" >&5
+echo "$as_me: error: \"Incorrect SCIP version. This build system is made for SCIP 2.0.x\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+#############################################################################
 #                       Check for external libraries                        #
 #############################################################################
 
@@ -24193,6 +24209,10 @@ esac
 
 CFLAGS="$CFLAGS $EXTRAFLAGS"
 CXXFLAGS="$CXXFLAGS $EXTRAFLAGS"
+
+#############################################################################
+#                                Finish up                                  #
+#############################################################################
 
                               ac_config_files="$ac_config_files Makefile coinscip.pc coinscip-uninstalled.pc"
 
